
name: Model Client

on:
  pull_request:
  
    branches: [ client ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  

    steps:
      - uses: actions/checkout@v2
      
      - name: Fetch target branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
      
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      
   
      #- name: Installing npm
       # run: brew install node

        
      - name: Installing nbdime
        run: pip3 install nbdime
        
      - name: git integration
        run: nbdime config-git --enable --global
        
      - name: navigate upwards
        run: cd ..

 
      - name: Comparison A and B
        #run: nbdiff-web client branch sample-report-gh.ipynb sample-report-gh.ipynb  
        #run: nbdiff client branch sample-report-gh.ipynb sample-report-gh.ipynb  
        #run: git difftool HEAD
        #run: nbdiff-web client branch HEAD
        run: nbdiff-web sample-report-gh.ipynb sample-report-gh.ipynb  



  
